apiVersion: apps/v1
kind: Deployment
metadata:
  name: reg-app
spec:
  selector:
    matchLabels:
      app: FE
  template:
    metadata:
      name: reg-app-pod
      labels:
        app: FE
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: reg-app-cont
        image: oladayur/cicd-demo:v2
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: app-sec


---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodb-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongodb
    spec:
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
             claimName: db-pvc
          #hostPath: 
           # path: /tmp/mongo
      containers:
        - name: mongodb-con
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
          - name: mongo-vol
            mountPath: /data/db
          envFrom:
          - secretRef:
              name: mongo-sec
